[book]
authors = ["Christophe Favergeon"]
language = "en"
src = "src"
title = "Intro to theorem proving for the embedded developer"

[output.html]
additional-css = [ "custom.css","pygments.css"]
mathjax-support = true
